### ISSUE TITLE
tcpser not getting a login prompt

### ISSUE THREAD

**Issue by hankbillings** [tschak909/platoterm64#22] opened 2018-12-10 06:20 UTC
On a C64, I'm attempting to use tcpser with a serial null modem with the following settings "tcpser -d /dev/ttyUSB0 -s 2400"  

I can dial irata online , i get a response and can see the "guest login: guest / guest" but there's nothing below to begin logging in and establishing an account.  It basically freezes. Bummer, I'm really exciting about this project.

Hank
kj4pvx@yahoo.com

**Comment by tschak909** [comment] 2018-12-10 06:53
Try adding -i "&K3" to your tcpser invocation.

**Comment by hankbillings** [comment] 2018-12-10 16:16
Thank you.  I tried &K0 and &K1 with no change.  However, when I use &K2, &K3, and &K4, i get a blank screen.  I don't get the sense that it's a modem issue (spider sense). I don't have an issue getting the login prompt from cyber1.org even though i have no idea how to setup an account for that one

**Comment by tschak909** [comment] 2018-12-10 18:02
very strange, I use tcpser with a Swiftlink on real hardware. Are you using
a Swiftlink or a user port RS232?

**Comment by hankbillings** [comment] 2018-12-10 22:00
I'm using the userport.  I ordered some new chips for my two swiftlinks, i think they got zapped in a move

**Comment by hankbillings** [comment] 2018-12-11 01:00
Here is the spot that is stops with no place to enter login info

![img_1215](https://user-images.githubusercontent.com/41028567/49771246-3f3cd980-fcb6-11e8-8f25-974a481bdf2a.jpg)

**Comment by tschak909** [comment] 2018-12-11 02:41
I just double checked the 1.0 release against my real C64, here:
https://www.youtube.com/watch?v=H3MPWUNsGls

You're the second person I've seen thus far who has expressed this problem,
very strange. It has something to do with the handshaking lines. How are
you connecting your user port to tcpser?

-Thom

**Comment by hankbillings** [comment] 2018-12-11 04:07
i don't know if this tells you anything but here's where tcpser endsup.


2018-12-11 04:13:27:-1226734480:DEBUG_X:Waiting for modem/control line/timer/socket activity
2018-12-11 04:13:27:-1226734480:DEBUG_X:Command Mode=0, Connection status=1
2018-12-11 04:13:27:-1226734480:DEBUG_X:Setting timer for break delay
2018-12-11 04:13:27:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:27:-1244662672:DEBUG:Read 52 bytes from socket
2018-12-11 04:13:27:-1226734480:DEBUG:Data available on serial port
2018-12-11 04:13:27:-1226734480:DEBUG:Read 3 bytes from serial port
2018-12-11 04:13:27:-1226734480:DEBUG_X:Waiting for modem/control line/timer/socket activity
2018-12-11 04:13:27:-1226734480:DEBUG_X:Command Mode=0, Connection status=1
2018-12-11 04:13:27:-1226734480:DEBUG_X:Setting timer for break delay
2018-12-11 04:13:28:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:28:-1244662672:DEBUG:Read 244 bytes from socket
2018-12-11 04:13:28:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:28:-1244662672:DEBUG:Read 256 bytes from socket
2018-12-11 04:13:28:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:28:-1244662672:DEBUG:Read 256 bytes from socket
2018-12-11 04:13:28:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:28:-1244662672:DEBUG:Read 195 bytes from socket
2018-12-11 04:13:28:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:28:-1244662672:DEBUG:Read 201 bytes from socket
2018-12-11 04:13:28:-1226734480:DEBUG:Initial Break Delay detected
2018-12-11 04:13:28:-1226734480:DEBUG_X:Waiting for modem/control line/timer/socket activity
2018-12-11 04:13:28:-1226734480:DEBUG_X:Command Mode=0, Connection status=1
2018-12-11 04:13:29:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:29:-1244662672:DEBUG:Read 249 bytes from socket
2018-12-11 04:13:29:-1244662672:DEBUG:Data available on socket
2018-12-11 04:13:29:-1244662672:DEBUG:Read 25 bytes from socket
2018-12-11 04:14:29:-1244662672:DEBUG:Data available on socket
2018-12-11 04:14:29:-1244662672:DEBUG:Read 35 bytes from socket
2018-12-11 04:14:30:-1244662672:DEBUG:Data available on socket
2018-12-11 04:14:30:-1244662672:DEBUG:Read 65 bytes from socket
2018-12-11 04:14:30:-1244662672:DEBUG:Data available on socket
2018-12-11 04:14:30:-1244662672:DEBUG:Read 123 bytes from socket

**Comment by hankbillings** [comment] 2018-12-11 04:09
I'm connecting two ways.  First with VIC-1011A (sweet) and second with a gglabs glinkusb-lt that works the same as the vic and uses the same drivers at 2400.

**Comment by tschak909** [comment] 2018-12-11 04:20
Do either of those hook up the RTS/CTS handshaking lines to $DD01 ?

-Thom

**Comment by hankbillings** [comment] 2018-12-11 04:53
That questions a little over my head.  I can tell you that this is the standard null modem connection that i use for most occasions, either using a console from a linux box or tcpser. I'm just don't know the answer to your question. I'm sorry.  I'm waiting on my account info to get approved so that i can test irata vs cyber1.  If it's irata specific that may tell us something.  Not sure what, but something.

**Comment by hankbillings** [comment] 2018-12-11 04:57
just figured out that the vic1011A blanks outimmediately after connection to irata.  So it doesn't even get to the Irata.online splash page , it just blanks out vs. the gglabs glinkusb-lt that gets to the picture above.  Maybe that tells us something.

**Comment by hankbillings** [comment] 2018-12-11 05:04
I can tell you that I do get the login prompt on cyber1

**Comment by tschak909** [comment] 2018-12-11 05:09
I have a funny feeling that RTS/CTS might not be hooked up. They are needed for PLATOTerm to work properly (because of the amount of processing required for incoming data, we often have to tell the modem to stop funneling data to the computer while we process data). 

-Thom

**Comment by tschak909** [comment] 2018-12-11 17:38
@hankbillings can you try the following pre-release? This adds asserting flow control on paint commands:
https://github.com/tschak909/platoterm64/releases/download/PLATOTerm-1.0/platoterm64-1_1-pre1-C64.d64

**Comment by hankbillings** [comment] 2018-12-11 19:30
the pre-version works! 

settings
tcpser -d /dev/ttyUSB0 -s 2400
UP2400 driver with the gglabs glinkusb-lt

**Comment by tschak909** [comment] 2018-12-11 19:51
OK, so buffer was overflowing, and you never saw the login prompt. Good.

-Thom

**Comment by hankbillings** [comment] 2018-12-11 20:01
I was able to succesfully login, however, on this version it automatically goes to the games menu and then locks up.  I have no idea what that means.  I can trouble shoot more later tonight if you wish.  I'm assuming those may be issues you've already worked out.

**Comment by tschak909** [comment] 2018-12-11 20:10
Can you press F3? Hmm.. -Thom

**Comment by hankbillings** [comment] 2018-12-11 22:58
no change when pressing F3?  it automatically goes to the game menu and conks out in a weird spot.  Very Strange.  This is where is freezes.
![img_1224](https://user-images.githubusercontent.com/41028567/49835784-4de6c780-fd6e-11e8-9e05-ad0d9ab8a7b5.jpg)

**Comment by tschak909** [comment] 2018-12-11 23:01
ok, so something is causing it to freeze. definitely a problem with the NMI
routine for userport modems. urgh.

-Thom

**Comment by hankbillings** [comment] 2018-12-13 04:06
just let me know when you want to do any testing for you.

**Comment by tschak909** [comment] 2018-12-13 04:19
Are you snagging a swiftlink?

-Thom

**Comment by hankbillings** [comment] 2018-12-13 23:23
I have two clones, but they both have stopped working and I assuming they got zapped during my last move. I have ordered new 6551p chips for both. Should be here in a week or so I hope. Have you considered the UP9600 driver used on novaterm and strike term?

**Comment by tschak909** [comment] 2018-12-14 00:03
Yes, but it needs to be ported to cc65, which is not something I currently
know how to do, will have to figure it out.
-Thom

**Comment by greg-king5** [comment] 2018-12-14 04:08
> Do either of those hook up the RTS/CTS handshaking lines to $DD01?

The schematic at http://www.zimmers.net/anonftp/pub/cbm/schematics/cartridges/userport/1011005.gif
says that the VIC-1011A does connect the handshaking lines.

**Comment by tschak909** [comment] 2018-12-14 04:27
Look at that. :)

@greg-king5 I'm definitely seeing an issue only with user port modems,
where PLATOTerm freezes, doesn't respond to anything but an NMI reset
(SHIFT-RESTORE)... This is a recent development, am wondering if maybe NMI
and TGI are biting it in the butt, again?

-Thom

**Comment by greg-king5** [comment] 2018-12-14 04:49
> @greg-king5, I'm definitely seeing an issue only with user port modems, where PLATOTerm freezes, doesn't respond to anything but an NMI reset (SHIFT-RESTORE)... This is a recent development, am wondering if maybe NMI and TGI are biting it in the butt, again?

I doubt it.  Nobody has changed them; they work together in the same way that they always have.

It might be a bug in Johan's driver that I forgot to mention.  It doesn't put its buffers in a safe place; there might be a clash between them and other program data.

**Comment by tschak909** [comment] 2018-12-14 04:56
What would be a safe place? -Thom (p.s. is it worth it to keep this driver,
or start over? The problem is, so many wifi modems are fucking user port
modems, and not supporting them literally means I lose at least half the
audience. :( )

**Comment by tschak909** [comment] 2018-12-14 06:41
Thanks @greg-king5 This worked a treat. If this works with multiple users, I'll cut a 1.1 release for the C64.
@hankbillings try this build and see if it's okay?
https://github.com/tschak909/platoterm64/releases/download/PLATOTerm-1.0/PLATOTerm64-1_1-pre2.d64.d64

-Thom

**Comment by hankbillings** [comment] 2018-12-14 10:28
ok...So, for some reason it still goes straight to the games menu, however, this time, the mouse 1541 isn't frozen, and I can select the options.  However, i can't execute the options, either by mouse click or entering them manually.  The mouse, will give the little info write up about the games, but won't bring up the option.  I get the prompt at the bottom to enter a lesson.  Also, if in the settings, I enter 1541, instead of just allowing the default that loads on startup, I get an error.  However, that's not new to this version. On a seperate note, I tried the ethernet option with my 64nic+, it wouldn't allow me to enter the ethernet option. I didn't try this on previous versions.
![img_1228](https://user-images.githubusercontent.com/41028567/49997871-be553a80-ff60-11e8-96d7-98357fb154e7.jpg)

**Comment by hankbillings** [comment] 2018-12-14 10:43
OK, due to my own lack of experience with buttons and instructions, the games will execute using the data button.  So....we're winning me thinks. however, both of the games i tried locked up within at least 30 seconds.  It still continues to automatically go straight to the games menu.

**Comment by beretta42** [comment] 2018-12-14 13:58
@hankbilkings: plato remembers where you are at In the menu system from login to login.

**Comment by hankbillings** [comment] 2018-12-14 16:45
Huh. That’s good to know

**Comment by tschak909** [comment] 2018-12-14 23:31
Ethernet support was jettisoned because IP65 needs support for tcp window
reaizing.

**Comment by hankbillings** [comment] 2018-12-15 15:10
Thom,

Once I backed out using the appropriate keys it is very usable.  Obviously some of the games aren't expected to work well at 2400, but I'll test those out and provide feedback as appropriate, I'll try to do that through irata on principle. I do think that the addition of the up9600 driver would be a welcome addition. I appreciate you jumping all over this over the last week.

Hank

**Comment by tschak909** [comment] 2018-12-15 15:29
Am glad. Documentation is definitely an issue, and it's something that's on my radar. I'm spending the majority of my time writing terminals, but this next year by summer, I'll be shifting into writing documentation.

I will close this ticket, for now.

**Closed as completed by tschak909** 2018-12-15 15:29 UTC
